baseURL = "https://tuoyiwen.github.io/"
languageCode = "en-us"
title = "Yiwen (Eavan)"

[params]
  bio = "Hi folks! I'm a PhD candidate in Organizational Behavior / Industrial Psychology. I'm interested in human-AI interaction, creativity, and innovation. I believe in human agency — technology is technology; the key is how we navigate it. Here I share my thoughts on this direction, relevant research progress in management, and tools that help enhance research efficiency."

[params.social]
  twitter = "https://x.com/evelyn_tuo"
  linkedin = "https://www.linkedin.com/feed/"
  email = "yiwentuotuo@gmail.com"

[markup.goldmark.renderer]
  unsafe = true
